version: '3.8'
services:
  web:
      build: 
        context: .
      restart: 
        on-failure
      environment:
        DJANGOSECRETKEY: $DJANGOSECRETKEY
        TZ: Europe/Moscow
      ports:
        - 8000:8000